"""
Google OAuth Service - Google authentication integration.

=============================================================================
GOOGLE OAUTH 2.0 AUTHORIZATION CODE FLOW WITH PKCE
=============================================================================

This service implements the Authorization Code Flow with PKCE (Proof Key for
Code Exchange), which is the recommended flow for Single Page Applications.

FLOW OVERVIEW:
==============

FRONTEND:
    1. Generate code_verifier (random string) and code_challenge (SHA256 hash)
    2. Redirect user to Google with code_challenge
    3. User logs in with Google
    4. Google redirects back with authorization code
    5. Frontend sends code + code_verifier + redirect_uri to backend

BACKEND (this service):
    1. Receive code, code_verifier, redirect_uri from frontend
    2. Exchange code for tokens with Google (using code_verifier)
    3. Verify the id_token from Google's response
    4. Extract user info and create/login user

WHY AUTHORIZATION CODE FLOW WITH PKCE?
======================================
- More secure: Code can only be exchanged once
- PKCE: Prevents authorization code interception attacks
- No client_secret needed on frontend (stays on backend)
- Recommended by OAuth 2.1 for SPAs

TOKEN EXCHANGE:
===============
POST https://oauth2.googleapis.com/token
{
    "code": "4/0ASc3gC21p4zbGhx...",
    "client_id": "your-client-id.apps...",
    "client_secret": "your-client-secret",
    "redirect_uri": "http://localhost:3000/auth/callback/google",
    "grant_type": "authorization_code",
    "code_verifier": "Srp1ogh23_MFrr3e6Bvg70votjH..."
}

Response:
{
    "access_token": "ya29.a0AfH6SMB...",
    "expires_in": 3599,
    "refresh_token": "1//0eXyz...",
    "scope": "openid email profile",
    "token_type": "Bearer",
    "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCI..."  <- We verify this
}

=============================================================================
"""

from typing import Optional

import requests
from django.conf import settings

from sessionops.utils.custom_logger import get_logger

logger = get_logger(__name__)

# Google OAuth endpoints
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"

# Try to import Google auth libraries
# If not installed, service will work but verification will fail
try:
    from google.auth.transport import requests as google_requests
    from google.oauth2 import id_token as google_id_token

    GOOGLE_AUTH_AVAILABLE = True
except ImportError:
    GOOGLE_AUTH_AVAILABLE = False
    logger.warning(
        "google-auth library not installed. "
        "Run: pip install google-auth google-auth-oauthlib"
    )


class GoogleOAuthError(Exception):
    """Custom exception for Google OAuth errors."""

    pass


class GoogleOAuthService:
    """
    Service for Google OAuth operations.

    Handles the Authorization Code Flow with PKCE:
    1. Exchange authorization code for tokens
    2. Verify the ID token
    3. Extract user information

    Configuration Required:
    =======================
    Add to your .env file:
        GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com
        GOOGLE_CLIENT_SECRET=your-client-secret

    Get credentials from:
        https://console.cloud.google.com/apis/credentials
    """

    @staticmethod
    def exchange_code_for_tokens(
        code: str,
        code_verifier: str,
        redirect_uri: str,
    ) -> Optional[dict]:
        """
        Exchange authorization code for tokens using PKCE.

        This is the core of the Authorization Code Flow:
        1. Frontend got an authorization code from Google
        2. We exchange it (with code_verifier) for tokens
        3. Google returns access_token, refresh_token, and id_token

        Args:
            code: Authorization code from Google redirect
            code_verifier: PKCE code verifier (generated by frontend)
            redirect_uri: Must match the redirect_uri used in authorization

        Returns:
            dict or None: Token response containing id_token, or None on error

        Token Response Contains:
            - access_token: For Google API calls (we don't use this)
            - refresh_token: For refreshing Google tokens (we don't use this)
            - id_token: JWT with user info (THIS IS WHAT WE NEED)
            - expires_in: Token expiry in seconds
            - token_type: Always "Bearer"

        Example:
            >>> tokens = GoogleOAuthService.exchange_code_for_tokens(
            ...     code="4/0ASc3gC21p4zbGhx...",
            ...     code_verifier="Srp1ogh23_MFrr3e6Bvg70votjH...",
            ...     redirect_uri="http://localhost:3000/auth/callback/google"
            ... )
            >>> if tokens:
            ...     id_token = tokens.get("id_token")
        """
        # Get credentials from settings
        client_id = getattr(settings, "GOOGLE_CLIENT_ID", None)
        client_secret = getattr(settings, "GOOGLE_CLIENT_SECRET", None)

        if not client_id:
            logger.error("GOOGLE_CLIENT_ID not configured in settings")
            raise GoogleOAuthError("Google OAuth not configured")

        if not client_secret:
            logger.error("GOOGLE_CLIENT_SECRET not configured in settings")
            raise GoogleOAuthError("Google OAuth not configured")

        # Prepare token exchange request
        # See: https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code
        token_data = {
            "code": code,
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uri": redirect_uri,
            "grant_type": "authorization_code",
            "code_verifier": code_verifier,
        }

        try:
            logger.info(f"Exchanging code for tokens with redirect_uri: {redirect_uri}")

            # Make POST request to Google's token endpoint
            response = requests.post(
                GOOGLE_TOKEN_ENDPOINT,
                data=token_data,
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=30,
            )

            # Check for errors
            if not response.ok:
                error_data = response.json()
                error_msg = error_data.get("error_description", error_data.get("error", "Unknown error"))
                logger.error(f"Google token exchange failed: {error_msg}")
                logger.error(f"Full error response: {error_data}")
                raise GoogleOAuthError(f"Token exchange failed: {error_msg}")

            tokens = response.json()
            logger.info("Successfully exchanged code for tokens")

            return tokens

        except requests.RequestException as e:
            logger.error(f"Network error during token exchange: {str(e)}")
            raise GoogleOAuthError(f"Network error: {str(e)}")
        except ValueError as e:
            logger.error(f"Invalid JSON response from Google: {str(e)}")
            raise GoogleOAuthError("Invalid response from Google")

    @staticmethod
    def verify_id_token(token: str) -> Optional[dict]:
        """
        Verify a Google ID token and return user info.

        This method:
        1. Fetches Google's public keys (cached by library)
        2. Verifies token signature
        3. Validates claims (issuer, audience, expiry)
        4. Returns decoded payload

        Args:
            token: Google ID token from frontend

        Returns:
            dict or None: Decoded token payload if valid, None if invalid

        Token Payload Contains:
            - sub: Google's unique ID for the user (NEVER changes)
            - email: User's email address
            - email_verified: Whether Google verified the email
            - name: User's full name
            - picture: URL to profile picture
            - given_name: First name
            - family_name: Last name

        Example:
            >>> data = GoogleOAuthService.verify_id_token("eyJhbGciOi...")
            >>> if data:
            ...     print(f"Email: {data['email']}")
            ...     print(f"Google ID: {data['sub']}")

        Security Notes:
        ===============
        - Always verify tokens server-side, never trust frontend
        - Check 'aud' claim matches YOUR client ID
        - Use 'sub' (not email) as primary Google identifier
        """
        if not GOOGLE_AUTH_AVAILABLE:
            logger.error("Google auth library not available")
            return None

        # Get client ID from settings
        client_id = getattr(settings, "GOOGLE_CLIENT_ID", None)

        if not client_id:
            logger.error(
                "GOOGLE_CLIENT_ID not configured in settings. "
                "Add GOOGLE_CLIENT_ID to your .env file."
            )
            return None

        try:
            # Verify the token
            # This function:
            # 1. Decodes the JWT
            # 2. Verifies signature using Google's public keys
            # 3. Validates standard claims (exp, iat, iss)
            # 4. Validates audience matches client_id
            #
            # google_requests.Request() is used to fetch Google's public keys
            # Keys are cached, so subsequent calls are fast
            id_info = google_id_token.verify_oauth2_token(
                token,
                google_requests.Request(),
                client_id,
            )

            # Additional validation
            # Issuer should be accounts.google.com or https://accounts.google.com
            issuer = id_info.get("iss", "")
            valid_issuers = ["accounts.google.com", "https://accounts.google.com"]

            if issuer not in valid_issuers:
                logger.warning(f"Invalid token issuer: {issuer}")
                return None

            logger.info(f"Google token verified for: {id_info.get('email')}")

            return id_info

        except ValueError as e:
            # Token is invalid (wrong format, expired, wrong audience, etc.)
            logger.warning(f"Google token verification failed: {str(e)}")
            return None
        except Exception as e:
            # Other errors (network, etc.)
            logger.error(f"Google token verification error: {str(e)}")
            return None

    @staticmethod
    def get_user_info_from_token(token_data: dict) -> dict:
        """
        Extract standardized user info from verified token data.

        This helper normalizes the Google token payload to a
        consistent format for our application.

        Args:
            token_data: Verified token payload from verify_id_token()

        Returns:
            dict: Standardized user info

        Example:
            >>> data = GoogleOAuthService.verify_id_token(token)
            >>> if data:
            ...     info = GoogleOAuthService.get_user_info_from_token(data)
            ...     print(info['display_name'])
        """
        # Get name, falling back to email local part if not provided
        email = token_data.get("email", "")
        name = token_data.get("name") or token_data.get("given_name") or email.split("@")[0]

        return {
            "google_sub": token_data.get("sub"),
            "email": email.lower(),
            "email_verified": token_data.get("email_verified", False),
            "display_name": name,
            "first_name": token_data.get("given_name", ""),
            "last_name": token_data.get("family_name", ""),
            "picture": token_data.get("picture", ""),
        }


# =============================================================================
# FRONTEND IMPLEMENTATION GUIDE
# =============================================================================
"""
To use Google Sign-In on your frontend:

1. ADD GOOGLE SCRIPT (in HTML head):
   <script src="https://accounts.google.com/gsi/client" async></script>

2. ADD SIGN-IN BUTTON (React example):

   // GoogleSignInButton.jsx
   import { useEffect } from 'react';

   export function GoogleSignInButton({ onSuccess }) {
     useEffect(() => {
       // Initialize Google Sign-In
       window.google.accounts.id.initialize({
         client_id: 'YOUR_CLIENT_ID.apps.googleusercontent.com',
         callback: handleCredentialResponse,
       });

       // Render the button
       window.google.accounts.id.renderButton(
         document.getElementById('google-signin-button'),
         { theme: 'outline', size: 'large' }
       );
     }, []);

     async function handleCredentialResponse(response) {
       // response.credential is the ID token
       const result = await fetch('/api/v1/auth/google', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify({ id_token: response.credential }),
       });

       const data = await result.json();
       if (result.ok) {
         // Store tokens and redirect
         localStorage.setItem('access_token', data.tokens.access_token);
         localStorage.setItem('refresh_token', data.tokens.refresh_token);
         onSuccess(data.user);
       }
     }

     return <div id="google-signin-button"></div>;
   }

3. GOOGLE CLOUD CONSOLE SETUP:
   a. Go to https://console.cloud.google.com/apis/credentials
   b. Create OAuth 2.0 Client ID (Web application)
   c. Add authorized JavaScript origins:
      - http://localhost:3000 (development)
      - https://yourdomain.com (production)
   d. Copy Client ID to your .env file as GOOGLE_CLIENT_ID
"""
