# Generated by Django 4.2 on 2026-04-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigAutoField(
                        help_text="Unique identifier for the user (auto-generated).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "user_display_name",
                    models.CharField(
                        help_text="The name displayed in the UI (e.g., 'John Doe').",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "user_login",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for login (often the email address).",
                        max_length=255,
                        unique=True,
                        verbose_name="Login Username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address (must be unique).",
                        max_length=255,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone number or other contact information.",
                        max_length=20,
                        null=True,
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        help_text="Role in the organization (e.g., 'admin', 'manager', 'user').",
                        max_length=50,
                        verbose_name="User Role",
                    ),
                ),
                (
                    "reporting_manager_user_login",
                    models.CharField(
                        blank=True,
                        help_text="Login identifier of the user's reporting manager.",
                        max_length=255,
                        null=True,
                        verbose_name="Reporting Manager Login",
                    ),
                ),
                (
                    "reporting_manager_role_code",
                    models.CharField(
                        blank=True,
                        help_text="Role code of the reporting manager.",
                        max_length=50,
                        null=True,
                        verbose_name="Reporting Manager Role",
                    ),
                ),
                (
                    "reporting_manager_user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User ID of the reporting manager.",
                        null=True,
                        verbose_name="Reporting Manager ID",
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        blank=True,
                        help_text="Who added this user to the system.",
                        max_length=255,
                        null=True,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where the user is located.",
                        max_length=100,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province where the user is located.",
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "center",
                    models.CharField(
                        blank=True,
                        help_text="Office center or branch location.",
                        max_length=100,
                        null=True,
                        verbose_name="Center",
                    ),
                ),
                (
                    "user_created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this user record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "user_updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this user record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-user_created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Unique identifier for this auth record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("password", "Password"), ("google_oauth", "Google OAuth")],
                        help_text="Type of authentication (password, google_oauth).",
                        max_length=20,
                        verbose_name="Auth Type",
                    ),
                ),
                (
                    "auth_identifier",
                    models.CharField(
                        help_text="The identifier for this auth method (usually email).",
                        max_length=255,
                        verbose_name="Auth Identifier",
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed password (only for password auth type).",
                        max_length=255,
                        null=True,
                        verbose_name="Password Hash",
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(
                        blank=True,
                        help_text="Google's unique subject identifier (from OAuth token).",
                        max_length=255,
                        null=True,
                        verbose_name="Google Subject ID",
                    ),
                ),
                (
                    "google_email_verified",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether Google has verified the user's email.",
                        null=True,
                        verbose_name="Google Email Verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this auth method was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this auth method was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag. If True, this auth method is disabled.",
                        verbose_name="Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this auth method was soft deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this auth method was last used for login.",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this authentication method belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_methods",
                        to="sessionops.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Auth",
                "verbose_name_plural": "User Auth Methods",
                "db_table": "user_auth",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_login"], name="idx_user_login"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_role"], name="idx_user_role"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["state", "city"], name="idx_user_location"),
        ),
        migrations.AddIndex(
            model_name="userauth",
            index=models.Index(fields=["user"], name="idx_user_auth_user_id"),
        ),
        migrations.AddIndex(
            model_name="userauth",
            index=models.Index(fields=["auth_type"], name="idx_user_auth_type"),
        ),
        migrations.AddIndex(
            model_name="userauth",
            index=models.Index(fields=["auth_identifier"], name="idx_user_auth_identifier"),
        ),
        migrations.AddIndex(
            model_name="userauth",
            index=models.Index(fields=["google_sub"], name="idx_user_auth_google_sub"),
        ),
        migrations.AddConstraint(
            model_name="userauth",
            constraint=models.UniqueConstraint(
                fields=("user", "auth_type"), name="uidx_user_auth_method"
            ),
        ),
        migrations.AddConstraint(
            model_name="userauth",
            constraint=models.UniqueConstraint(
                fields=("auth_type", "auth_identifier"), name="uidx_auth_identity"
            ),
        ),
    ]
