# Generated by Django 4.2 on 2026-04-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0002_add_user_is_active"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userauth",
            name="uidx_user_auth_method",
        ),
        migrations.RemoveConstraint(
            model_name="userauth",
            name="uidx_auth_identity",
        ),
        migrations.RemoveIndex(
            model_name="userauth",
            name="idx_user_auth_user_id",
        ),
        migrations.RemoveIndex(
            model_name="userauth",
            name="idx_user_auth_type",
        ),
        migrations.RemoveIndex(
            model_name="userauth",
            name="idx_user_auth_identifier",
        ),
        migrations.RemoveIndex(
            model_name="userauth",
            name="idx_user_auth_google_sub",
        ),
        migrations.RemoveField(
            model_name="userauth",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="userauth",
            name="google_sub",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this user record was soft-deleted.",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed the soft-delete operation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.user",
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Updated on each successful authentication.",
                null=True,
                verbose_name="Last Login At",
            ),
        ),
        migrations.AddField(
            model_name="userauth",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.user",
            ),
        ),
        migrations.AddField(
            model_name="userauth",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated role string synced from Hasura. Example: 'CO Part Time,Wingman'. Parsed at runtime to determine permissions.",
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="auth_identifier",
            field=models.CharField(
                help_text="Lookup key for this auth method. Google: google_sub from id_token. Password: lowercased user_login.",
                max_length=255,
                verbose_name="Auth Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="auth_type",
            field=models.CharField(
                choices=[("password", "Password"), ("google", "Google")],
                help_text="Type of authentication: 'google' or 'password'.",
                max_length=16,
                verbose_name="Auth Type",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="google_email_verified",
            field=models.BooleanField(
                blank=True,
                help_text="Whether Google verified the email. Populated only for auth_type='google'.",
                null=True,
                verbose_name="Google Email Verified",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this auth method was last used to sign in.",
                null=True,
                verbose_name="Last Used At",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="password_hash",
            field=models.CharField(
                blank=True,
                help_text="Argon2id hash of the user's password. Populated only for auth_type='password'.",
                max_length=255,
                null=True,
                verbose_name="Password Hash",
            ),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userauth",
            name="user",
            field=models.ForeignKey(
                help_text="The user this authentication method belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auth_methods",
                to="sessionops.user",
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="userauth",
            index=models.Index(fields=["user", "auth_type"], name="user_auth_user_id_40f031_idx"),
        ),
        migrations.AddConstraint(
            model_name="userauth",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("auth_type", "auth_identifier"),
                name="uniq_active_auth_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="userauth",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "auth_type"),
                name="uniq_active_auth_per_user_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="userauth",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("auth_type", "google"), ("password_hash__isnull", True)),
                    models.Q(("auth_type", "password"), ("password_hash__isnull", False)),
                    _connector="OR",
                ),
                name="auth_type_field_integrity",
            ),
        ),
    ]
