# Generated by Django 4.2 on 2026-04-29 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0004_add_password_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("users_fetched", models.IntegerField(default=0)),
                ("users_created", models.IntegerField(default=0)),
                ("users_updated", models.IntegerField(default=0)),
                ("partners_fetched", models.IntegerField(default=0)),
                ("partners_created", models.IntegerField(default=0)),
                ("partners_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this row was last refreshed from Hasura.",
                null=True,
                verbose_name="Synced At",
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("partner_id", models.BigIntegerField(db_index=True, unique=True)),
                ("partner_name", models.CharField(max_length=255)),
                ("co_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("co_name", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line_1", models.TextField(blank=True, null=True)),
                ("address_line_2", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("city_id", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("state_id", models.IntegerField(blank=True, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("school_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "partner_affiliation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("poc_name", models.CharField(blank=True, max_length=255, null=True)),
                ("poc_email", models.CharField(blank=True, max_length=255, null=True)),
                ("poc_designation", models.CharField(blank=True, max_length=255, null=True)),
                ("poc_contact", models.CharField(blank=True, max_length=50, null=True)),
                ("mou_sign_date", models.DateField(blank=True, null=True)),
                ("mou_start_date", models.DateField(blank=True, null=True)),
                ("mou_end_date", models.DateField(blank=True, null=True)),
                ("mou_url", models.TextField(blank=True, null=True)),
                ("converted", models.BooleanField(default=False)),
                ("crm_partner_removed", models.BooleanField(default=False)),
                ("latest_conversion_stage", models.CharField(blank=True, max_length=50, null=True)),
                ("lead_source", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_first_contact", models.DateTimeField(blank=True, null=True)),
                ("confirmed_child_count", models.IntegerField(blank=True, null=True)),
                ("total_child_count", models.IntegerField(blank=True, null=True)),
                ("classes", models.TextField(blank=True, null=True)),
                ("partner_created_date", models.DateTimeField(blank=True, null=True)),
                ("partner_updated_date", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "partner",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["co_id"], name="partner_co_id_d47262_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["partner_updated_date"], name="partner_partner_4b4fce_idx"),
        ),
    ]
