# Generated by Django 4.2 on 2026-05-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0008_password_reset_token_invalidation_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("academic_year_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "academic_year",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("child_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("mother_tongue", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_enrollment", models.DateField(blank=True, null=True)),
                ("mad_joining_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "child",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=20)),
                ("class_code", models.CharField(max_length=4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "class",
                "ordering": ["class_code"],
            },
        ),
        migrations.CreateModel(
            name="SchoolAcademicYear",
            fields=[
                ("school_academic_year_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year_id",
                    models.ForeignKey(
                        db_column="academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_academic_year",
            },
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the token is closed (consumed by user or superseded by system).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("school_class_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_academic_year_id",
                    models.ForeignKey(
                        db_column="school_academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_class",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("program_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("program_name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "program",
            },
        ),
        migrations.CreateModel(
            name="ClassSection",
            fields=[
                ("class_section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                        ],
                        max_length=1,
                    ),
                ),
                ("section_name", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_class_id",
                    models.ForeignKey(
                        db_column="school_class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "class_section",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="program_id",
            field=models.ForeignKey(
                db_column="program_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="sessionops.program",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.user",
            ),
        ),
        migrations.CreateModel(
            name="ChildRemovalLog",
            fields=[
                ("child_removal_log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("co_id", models.BigIntegerField()),
                ("school_id", models.BigIntegerField(db_index=True)),
                (
                    "removed_reason",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("duplicate_entry", "Duplicate entry"),
                            ("wrong_school_class", "Added to wrong school/class by mistake"),
                            ("transferred", "Transferred to another school"),
                            ("dropped_out", "Dropped out of school"),
                            ("family_declined", "Family does not want the child enrolled"),
                            ("child_declined", "Child no longer interested in participating"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_details", models.TextField(blank=True, null=True)),
                ("removed_datetime", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        db_column="child_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.child",
                    ),
                ),
            ],
            options={
                "db_table": "child_removal_log",
            },
        ),
        migrations.CreateModel(
            name="ChildProgram",
            fields=[
                ("child_program_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        db_column="child_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.child",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        db_column="program_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.program",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "child_program",
            },
        ),
        migrations.CreateModel(
            name="ChildClassSection",
            fields=[
                ("child_class_section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        db_column="child_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.child",
                    ),
                ),
                (
                    "class_section_id",
                    models.ForeignKey(
                        db_column="class_section_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.classsection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "child_class_section",
            },
        ),
        migrations.CreateModel(
            name="ChildClass",
            fields=[
                ("child_class_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        db_column="child_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.child",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_class_id",
                    models.ForeignKey(
                        db_column="school_class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "child_class",
            },
        ),
        migrations.CreateModel(
            name="BatchChild",
            fields=[
                ("batch_child_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        db_column="child_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.child",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_academic_year_id",
                    models.ForeignKey(
                        db_column="school_academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "batch_child",
            },
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed", False)),
                fields=("school_id", "school_academic_year_id", "class_id"),
                name="uniq_school_class_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolacademicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed", False)),
                fields=("school_id", "academic_year_id"),
                name="uniq_school_academic_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="classsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed", False)),
                fields=("school_class_id", "section_code"),
                name="uniq_section_per_school_class",
            ),
        ),
        migrations.AddIndex(
            model_name="childremovallog",
            index=models.Index(
                fields=["child_id", "is_active"], name="child_remov_child_i_079ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childclasssection",
            index=models.Index(
                fields=["child_id", "is_active"], name="child_class_child_i_3985b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childclasssection",
            index=models.Index(
                fields=["class_section_id", "is_active"], name="child_class_class_s_c9c479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childclass",
            index=models.Index(
                fields=["child_id", "is_active"], name="child_class_child_i_9c5f4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childclass",
            index=models.Index(
                fields=["school_class_id", "is_active"], name="child_class_school__bc3e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="child",
            index=models.Index(
                fields=["school_id", "is_active", "removed"], name="child_school__709cf2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="uniq_active_academic_year",
            ),
        ),
    ]
