# Generated by Django 4.2 on 2026-05-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0012_fix_child_schema_drift"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerWorknode",
            fields=[
                ("partner_worknode_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("partner_id", models.CharField(db_index=True, max_length=100)),
                ("worknode_id", models.IntegerField(db_index=True)),
                ("city_name", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("co_name", models.TextField(blank=True, null=True)),
                ("chapter_name", models.CharField(blank=True, max_length=200, null=True)),
                ("engine", models.CharField(blank=True, max_length=100, null=True)),
                ("chapter_status", models.CharField(blank=True, max_length=50, null=True)),
                ("sourcing_campaign_code", models.TextField(blank=True, null=True)),
                ("campaign_name", models.CharField(blank=True, max_length=200, null=True)),
                ("fundraiser_id", models.CharField(blank=True, max_length=100, null=True)),
                ("fundraiser_name", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partner_worknode",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="worknode_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Worknode platform ID synced from Hasura. Links this user to a school via PartnerWorknode.",
                null=True,
                verbose_name="Worknode ID",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerworknode",
            index=models.Index(fields=["partner_id"], name="partner_wor_partner_3fb39a_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerworknode",
            index=models.Index(fields=["worknode_id"], name="partner_wor_worknod_1e7877_idx"),
        ),
    ]
