# Generated by Django 4.2 on 2026-05-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0013_m3_user_worknode_partner_worknode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        db_column="program_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.program",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("slot_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("slot_name", models.CharField(max_length=100)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("recurring", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_academic_year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "slot",
            },
        ),
        migrations.CreateModel(
            name="SchoolVolunteer",
            fields=[
                ("school_volunteer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_academic_year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "volunteer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_volunteer_entries",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_volunteer",
            },
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["school_id", "is_active", "removed"], name="slot_school__b8d925_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["school_id", "day_of_week"], name="slot_school__d50558_idx"),
        ),
        migrations.AddIndex(
            model_name="schoolvolunteer",
            index=models.Index(
                fields=["school_id", "is_active", "removed"], name="school_volu_school__e3fd1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolvolunteer",
            index=models.Index(
                fields=["volunteer_id", "is_active", "removed"],
                name="school_volu_volunte_de13f3_idx",
            ),
        ),
    ]
