# Generated by Django 4.2 on 2026-05-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0014_m3_subject_school_volunteer_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSectionSubject",
            fields=[
                (
                    "class_section_subject_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sessionops.classsection"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sessionops.subject"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "class_section_subject",
            },
        ),
        migrations.CreateModel(
            name="SlotClassSection",
            fields=[
                ("slot_class_section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sessionops.classsection"
                    ),
                ),
                (
                    "class_section_subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.classsectionsubject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "slot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sessionops.slot"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "slot_class_section",
            },
        ),
        migrations.CreateModel(
            name="SlotClassSectionVolunteer",
            fields=[
                (
                    "slot_class_section_volunteer_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "slot_class_section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.slotclasssection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "volunteer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slot_class_assignments",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "slot_class_section_volunteer",
            },
        ),
        migrations.CreateModel(
            name="ChildSubject",
            fields=[
                ("child_subject_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sessionops.child"
                    ),
                ),
                (
                    "class_section_subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.classsectionsubject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "child_subject",
            },
        ),
        migrations.AddIndex(
            model_name="slotclasssectionvolunteer",
            index=models.Index(
                fields=["slot_class_section_id", "is_active", "removed"],
                name="slot_class__slot_cl_429696_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slotclasssectionvolunteer",
            index=models.Index(
                fields=["volunteer_id", "is_active", "removed"],
                name="slot_class__volunte_10ac29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slotclasssection",
            index=models.Index(
                fields=["slot_id", "is_active", "removed"], name="slot_class__slot_id_cc60bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsectionsubject",
            index=models.Index(
                fields=["class_section_id", "is_active", "removed"],
                name="class_secti_class_s_2c0400_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="childsubject",
            index=models.Index(
                fields=["child_id", "is_active", "removed"], name="child_subje_child_i_1b5f26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childsubject",
            index=models.Index(
                fields=["class_section_subject_id", "is_active", "removed"],
                name="child_subje_class_s_f1d8a1_idx",
            ),
        ),
    ]
