# Generated by Django 4.2 on 2026-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0015_classsectionsubject_slotclasssection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncrun",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("users", "Users"),
                    ("partners", "Partners"),
                    ("partner_worknode", "Partner Worknode"),
                    ("all", "All"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
