# Generated by Django 4.2 on 2026-06-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0016_sync_run_add_partner_worknode_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSessionDetails",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "school_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_session_details",
            },
        ),
        migrations.AddIndex(
            model_name="schoolsessiondetails",
            index=models.Index(
                fields=["school_id", "is_active", "removed"], name="school_sess_school__80f6f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsessiondetails",
            index=models.Index(
                fields=["school_academic_year"], name="school_sess_school__ef9879_idx"
            ),
        ),
    ]
