# Generated by Django 4.2 on 2026-06-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0017_session_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                ("school_holiday_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("school_id", models.BigIntegerField(db_index=True)),
                (
                    "holiday_reason",
                    models.CharField(
                        choices=[
                            ("mad_event", "MAD event (eg: YEC, etc)"),
                            ("holidays", "Holidays"),
                            ("cancelled_from_school_end", "Cancelled from school's end"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("holiday_description", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_holiday",
            },
        ),
        migrations.AddIndex(
            model_name="schoolholiday",
            index=models.Index(
                fields=["school_id", "is_active", "removed"], name="school_holi_school__65343d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolholiday",
            index=models.Index(
                fields=["school_id", "start_date", "end_date"],
                name="school_holi_school__cabec7_idx",
            ),
        ),
    ]
