# Generated by Django 4.2 on 2026-06-05 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0019_extend_sync_run"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="sync_run_run_typ_8ee96e_idx",
            old_name="sync_run_run_type_idx",
        ),
        migrations.RenameIndex(
            model_name="syncrun",
            new_name="sync_run_status_0cb6ca_idx",
            old_name="sync_run_status_idx",
        ),
    ]
