# Generated by Django 4.2 on 2026-06-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0021_sync_run_cursor_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncrun",
            name="cursor_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RealtimeSyncLog",
            fields=[
                ("realtime_sync_log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id_from_source", models.IntegerField(db_index=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("manual_admin", "Manual trigger by admin"),
                            ("realtime_webhook", "Realtime via n8n / webhook"),
                            ("cron_fallback", "Cron-based fallback sync"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("insert", "User created"),
                            ("update", "User updated"),
                            ("deactivate", "User deactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            (
                                "partial_success",
                                "Partial — common fields only, worknode cascade skipped",
                            ),
                            ("failed", "Failed"),
                            ("skipped_role_not_allowed", "Skipped — role not in allowlist"),
                            ("skipped_no_change", "Skipped — no meaningful changes"),
                            ("skipped_stale", "Skipped — incoming data older than stored"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("user_created", "New user inserted"),
                            ("common_fields_updated", "Common field update only"),
                            ("worknode_added", "Worknode_id added with cascade"),
                            ("worknode_updated", "Worknode_id updated with cascade"),
                            ("worknode_removed", "Worknode_id removed with cascade"),
                            ("user_deactivated", "User deactivated with cascade"),
                            ("no_change", "No action — same as before"),
                            (
                                "no_school_found_for_worknode",
                                "Common fields updated, worknode cascade skipped",
                            ),
                            ("failed", "Failed mid-processing"),
                        ],
                        max_length=40,
                    ),
                ),
                ("error_details", models.TextField(blank=True, null=True)),
                ("pre_snapshot", models.JSONField(blank=True, null=True)),
                ("incoming_payload", models.JSONField(blank=True, null=True)),
                ("field_changes", models.JSONField(blank=True, null=True)),
                ("cascaded_changes", models.JSONField(blank=True, null=True)),
                ("rules_fired", models.JSONField(blank=True, null=True)),
                ("deferred_operations", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_sync_log",
            },
        ),
        migrations.AddIndex(
            model_name="realtimesynclog",
            index=models.Index(
                fields=["user_id_from_source", "received_at"], name="realtime_sy_user_id_1460d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimesynclog",
            index=models.Index(
                fields=["status", "received_at"], name="realtime_sy_status_6c9d28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimesynclog",
            index=models.Index(
                fields=["sync_type", "received_at"], name="realtime_sy_sync_ty_d3564c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimesynclog",
            index=models.Index(fields=["external_event_id"], name="realtime_sy_externa_bf86f1_idx"),
        ),
    ]
