# Generated by Django 4.2 on 2026-07-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0023_school_volunteer_nullable_say_and_created_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classsection",
            name="uniq_section_per_school_class",
        ),
        migrations.AlterField(
            model_name="classsection",
            name="school_class_id",
            field=models.ForeignKey(
                blank=True,
                db_column="school_class_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sessionops.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="classsection",
            name="section_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="classsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed", False), ("section_code__isnull", False)),
                fields=("school_class_id", "section_code"),
                name="uniq_section_per_school_class",
            ),
        ),
    ]
