# Generated by Django 4.2 on 2026-07-03 07:29

from django.db import migrations, models


def backfill_section_display_name(apps, schema_editor):
    ClassSection = apps.get_model("sessionops", "ClassSection")
    ClassSection.objects.filter(section_display_name__isnull=True).update(
        section_display_name=models.F("section_name")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0024_m6_class_section_nullable_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsection",
            name="section_display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="classsection",
            name="section_name",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(backfill_section_display_name, noop_reverse),
    ]
