# Generated by Django 4.2 on 2026-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0025_m6_section_display_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="classsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed", False)),
                fields=("school_id", "section_name"),
                name="class_section_slug_per_school",
            ),
        ),
    ]
