# Generated by Django 4.2 on 2026-07-03 07:30

from django.db import migrations


def seed_foundation_subject(apps, schema_editor):
    Program = apps.get_model("sessionops", "Program")
    Subject = apps.get_model("sessionops", "Subject")
    alias = schema_editor.connection.alias

    # Reuse the existing "Foundation Program" row (seeded by db_startup.py /
    # seed_m2_catalog.py) — the same Program that already backs the legacy
    # "Foundation Day 1" / "Foundation Day 2" subjects and the hardcoded
    # FOUNDATION_PROGRAM_ID=1 in services/children/enroll.py.
    program, _ = Program.objects.using(alias).get_or_create(
        program_name="Foundation Program",
        defaults={"is_active": True},
    )
    Subject.objects.using(alias).get_or_create(
        subject_name="Foundation",
        defaults={"program_id": program},
    )


def noop_reverse(apps, schema_editor):
    # Intentionally a no-op: if M6 is rolled back, deleting the seeded row is
    # safe in principle, but leaving it is harmless and avoids ever deleting a
    # Subject row that later M6-era ClassSectionSubject rows may reference.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0026_m6_section_slug_unique_per_school"),
    ]

    operations = [
        migrations.RunPython(seed_foundation_subject, noop_reverse),
    ]
