# Generated by Django 4.2 on 2026-07-03 07:30

from django.db import migrations


def noop_seed_foundation_subject(apps, schema_editor):
    """
    Intentionally neutered (2026-09-02): this used to auto-create a "Foundation"
    Subject row on every fresh deploy. Subject is NOT part of the M7 Bubble
    migration pipeline (decision #18 — class_section_subject/child_subject's
    subject_id FK checks validate against whatever Subject rows already exist,
    rather than importing subject itself). In practice Bubble has several real
    historical subjects (not just one) with child_subject/class_section_subject
    rows FK'd to their real subject_id values, so auto-seeding a "Foundation"
    row here — with whatever PK Django's sequence happened to assign — collided
    with that: either the later data import's insert failed outright on the
    subject_name unique constraint, or (worse) an upsert silently renamed the
    seeded row away from "Foundation", breaking get_foundation_subject() for
    every slot-class create/edit.
    The exact same "Foundation" name+row for get_foundation_subject() to find
    now comes from the external migration itself (renaming one of the existing
    legacy subject rows in place, same subject_id, so historical FKs stay
    intact) — never from this migration. Left as a no-op rather than deleted:
    0028 depends on this migration by name, and deleting it would break the
    migration graph on any fresh database.
    """


def noop_reverse(apps, schema_editor):
    # Already a no-op before this migration was neutered; nothing to reverse.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0026_m6_section_slug_unique_per_school"),
    ]

    operations = [
        migrations.RunPython(noop_seed_foundation_subject, noop_reverse),
    ]
