# Generated by Django 4.2 on 2026-08-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0029_class_section_slug_active_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsection",
            name="school_academic_year_id",
            field=models.ForeignKey(
                blank=True,
                db_column="school_academic_year_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sessionops.schoolacademicyear",
            ),
        ),
    ]
