"""
F-M7-1: generic migration upsert engine unit tests.

Covers services/migration/generic.py directly (no HTTP layer). Endpoint-level
integration tests live in test_migration_endpoints.py.
"""

import pytest

from sessionops.models import Class, Program, User
from sessionops.services.migration.generic import migrate_row
from sessionops.services.migration.registry import TABLE_CONFIGS

MIGRATION_ACTOR_USER_ID = 1924616

_PID = iter(range(910_000, 920_000))


def _pid() -> int:
    return next(_PID)


@pytest.fixture(autouse=True)
def _ensure_migration_actor(db):
    """system_user.py looks up user_id=1924616 (a real person in dev/prod).
    pytest runs against its own fresh test database (see settings.py's
    _TESTING branch), so that specific row doesn't exist there by default —
    seed an equivalent row for the test's transaction."""
    User.objects.get_or_create(
        user_id=MIGRATION_ACTOR_USER_ID,
        defaults={
            "user_login": "gaurav.thwait@makeadiff.in",
            "user_display_name": "Gaurav Thwait",
            "email": "gaurav.thwait@makeadiff.in",
            "is_active": True,
        },
    )


@pytest.mark.django_db
def test_migrate_row_inserts_new_pk():
    pk = _pid()
    result = migrate_row(
        TABLE_CONFIGS["programs"],
        {
            "program_id": pk,
            "program_name": f"Prog {pk}",
            "is_active": True,
            "removed": False,
        },
    )
    assert result.status == "inserted"
    assert result.pk == pk

    obj = Program.objects.get(program_id=pk)
    assert obj.program_name == f"Prog {pk}"
    assert obj.created_by_id == MIGRATION_ACTOR_USER_ID


@pytest.mark.django_db
def test_migrate_row_updates_existing_pk_with_changes():
    pk = _pid()
    migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "Old Name"})
    result = migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "New Name"})

    assert result.status == "updated"
    assert result.changes == ["program_name"]
    assert Program.objects.get(program_id=pk).program_name == "New Name"


@pytest.mark.django_db
def test_migrate_row_idempotent_rerun():
    pk = _pid()
    payload = {"program_id": pk, "program_name": "Same Name"}
    migrate_row(TABLE_CONFIGS["programs"], payload)
    result = migrate_row(TABLE_CONFIGS["programs"], payload)

    assert result.status == "updated"
    assert result.changes == []


@pytest.mark.django_db
def test_migrate_row_required_fk_missing_returns_skipped_orphan_fk():
    pk = _pid()
    result = migrate_row(
        TABLE_CONFIGS["classes"],
        {
            "class_id": pk,
            "class_name": "X",
            "class_code": f"X{pk % 10}",
            "program_id": 999_999_999,
        },
    )
    assert result.status == "skipped"
    assert result.reason == "orphan_fk"
    assert "program_id" in result.detail
    assert not Class.objects.filter(class_id=pk).exists()


@pytest.mark.django_db
def test_migrate_row_sets_created_by_to_migration_actor_on_insert():
    pk = _pid()
    migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "Audit Check"})
    obj = Program.objects.get(program_id=pk)
    assert obj.created_by_id == MIGRATION_ACTOR_USER_ID


@pytest.mark.django_db
def test_migrate_row_does_not_overwrite_created_by_on_update():
    pk = _pid()
    migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "V1"})
    migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "V2"})

    obj = Program.objects.get(program_id=pk)
    assert obj.created_by_id == MIGRATION_ACTOR_USER_ID
    assert obj.updated_by_id == MIGRATION_ACTOR_USER_ID


@pytest.mark.django_db
def test_migrate_row_explicit_pk_preserved_not_autogenerated():
    pk = _pid()
    migrate_row(TABLE_CONFIGS["programs"], {"program_id": pk, "program_name": "Explicit PK"})
    assert Program.objects.filter(program_id=pk).exists()


@pytest.mark.django_db
def test_migrate_row_real_fk_check_passes_and_creates_row():
    program_pk = _pid()
    migrate_row(
        TABLE_CONFIGS["programs"],
        {"program_id": program_pk, "program_name": "Parent Program"},
    )

    class_pk = _pid()
    result = migrate_row(
        TABLE_CONFIGS["classes"],
        {
            "class_id": class_pk,
            "class_name": "Grade X",
            "class_code": f"G{class_pk % 10}",
            "program_id": program_pk,
        },
    )
    assert result.status == "inserted"
    cls = Class.objects.get(class_id=class_pk)
    assert cls.program_id_id == program_pk


@pytest.mark.django_db
@pytest.mark.parametrize("table_key", list(TABLE_CONFIGS.keys()))
def test_table_configs_registry_entries_are_wired_correctly(table_key):
    """Catches config-registry typos (wrong model, wrong pk_field, FK target
    mismatch) across every registered table with one parametrized pass,
    instead of one hand-written near-duplicate test per table."""
    config = TABLE_CONFIGS[table_key]
    assert config.model._meta.get_field(config.pk_field) is not None
    for check in (*config.required_fks, *config.optional_fks):
        assert check.field, f"{table_key}: FkCheck.field must be set"
        if check.kind == "real_fk":
            assert check.target_model is not None, f"{table_key}: real_fk check needs target_model"
